[package]
name = "fake-system"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
nix = { version = "0.29", default-features = false, features = [
    "mman",
    "process",
    "ptrace",
    "signal",
    "uio",
    "user",
] }
thiserror = "1"
